const TEMPLATE_EMAIL_VERIFIED = `<!doctypehtml><html lang=es><meta charset=UTF-8><meta content="IE=edge"http-equiv=X-UA-Compatible><meta content="width=device-width,initial-scale=1"name=viewport><title>Verificación de correo</title><style>body{font-family:Inter,sans-serif;background-color:#f3f4f6;margin:0;padding:0;display:flex;justify-content:center;align-items:center;height:100vh;color:#333}.container{background:#fff;border-radius:10px;max-width:600px;margin:20px auto;padding:20px;box-shadow:0 8px 32px rgba(0,0,0,.2);text-align:center}h1{color:#333;font-size:24px;margin-bottom:16px}p{color:#555;font-size:16px;margin-bottom:24px}.verification-code{font-size:28px;color:#f9c74f;background-color:#f3f3f3;padding:10px;border-radius:8px;display:inline-block;margin-bottom:20px}.button{background-color:#f9c74f;color:#fff;padding:10px 20px;text-decoration:none;font-size:16px;border-radius:5px;display:inline-block;transition:background-color .3s ease}.button:hover{background-color:#e5b800}.footer{font-size:14px;color:#777;margin-top:20px}.footer a{color:#f9c74f;text-decoration:none}.footer a:hover{text-decoration:underline}</style><div class=container><h1>Verificación de correo</h1><p>Gracias por registrarte. Usa el siguiente código para verificar tu correo electrónico:<div class=verification-code>{{code}}</div><p>Si no solicitaste este correo, puedes ignorarlo.</p><a href=# class=button>Validar correo</a><div class=footer><p>¿No recibiste el código? <a href=#>Reenviar código</a></div></div>`;

const TEMPLATE_EMAIL_WELCOME = `<!doctypehtml><html lang=es><meta charset=UTF-8><meta content="IE=edge"http-equiv=X-UA-Compatible><meta content="width=device-width,initial-scale=1"name=viewport><title>Bienvenida</title><style>body{font-family:Inter,sans-serif;background-color:#f3f4f6;margin:0;padding:0;display:flex;justify-content:center;align-items:center;height:100vh;color:#333}.container{background:#fff;border-radius:10px;max-width:600px;margin:20px auto;padding:30px;box-shadow:0 8px 32px rgba(0,0,0,.2);text-align:center}h1{color:#333;font-size:28px;margin-bottom:16px}p{color:#555;font-size:16px;margin-bottom:20px}.welcome-message{font-size:18px;color:#333;margin-bottom:24px;line-height:1.5}.button{background-color:#f9c74f;color:#fff;padding:12px 25px;text-decoration:none;font-size:16px;border-radius:5px;display:inline-block;transition:background-color .3s ease}.button:hover{background-color:#e5b800}.footer{font-size:14px;color:#777;margin-top:20px}.footer a{color:#f9c74f;text-decoration:none}.footer a:hover{text-decoration:underline}</style><div class=container><h1>¡Bienvenido a {{appName}}!</h1><p>Hola {{name}},<p class=welcome-message>Estamos encantados de tenerte a bordo. Ahora formas parte de una comunidad que busca {{details}}. Explora las funcionalidades que hemos creado para ti, y empieza a disfrutar de una experiencia personalizada.</p><a href="[Enlace a la página de inicio]"class=button>Comienza Ahora</a><div class=footer><p>Si tienes alguna pregunta, no dudes en <a href=mailto:soporte@tu-dominio.com>contactarnos</a>.</div></div>`;

const TEMPLATE_EMAIL_FORGOT_PASSWORD = `<!doctypehtml><html lang=es><meta charset=UTF-8><meta content="IE=edge"http-equiv=X-UA-Compatible><meta content="width=device-width,initial-scale=1"name=viewport><title>Recuperar contraseña</title><style>body{font-family:Inter,sans-serif;background-color:#f3f4f6;margin:0;padding:0;display:flex;justify-content:center;align-items:center;height:100vh;color:#333}.container{background:#fff;border-radius:10px;max-width:600px;margin:20px auto;padding:30px;box-shadow:0 8px 32px rgba(0,0,0,.2);text-align:center}h1{color:#333;font-size:24px;margin-bottom:16px}p{color:#555;font-size:16px;margin-bottom:20px}.reset-message{font-size:16px;color:#555;margin-bottom:24px;line-height:1.5}.button{background-color:#f9c74f;color:#fff;padding:12px 25px;text-decoration:none;font-size:16px;border-radius:5px;display:inline-block;transition:background-color .3s ease}.button:hover{background-color:#e5b800}.footer{font-size:14px;color:#777;margin-top:20px}.footer a{color:#f9c74f;text-decoration:none}.footer a:hover{text-decoration:underline}.note{font-size:14px;color:#777;margin-top:20px}</style><div class=container><h1>¿Olvidaste tu contraseña?</h1><p>Hola {{name}},<p class=reset-message>Parece que has solicitado restablecer tu contraseña. Haz clic en el botón de abajo para crear una nueva contraseña:</p><a class=button href="{{url}}">Restablecer Contraseña</a><div class=footer><p>Si no solicitaste este cambio, puedes ignorar este correo.</div><p class=note>Este enlace es válido por 1 hora.</div>`;

const TEMPLATE_EMAIL_SUCCESS_FORGOT_PASSWORD = `<!doctypehtml><html lang=es><meta charset=UTF-8><meta content="IE=edge"http-equiv=X-UA-Compatible><meta content="width=device-width,initial-scale=1"name=viewport><title>Cambio de contraseña exitoso</title><style>body{font-family:Inter,sans-serif;background-color:#f3f4f6;margin:0;padding:0;display:flex;justify-content:center;align-items:center;height:100vh;color:#333}.container{background:#fff;border-radius:10px;max-width:600px;margin:20px auto;padding:30px;box-shadow:0 8px 32px rgba(0,0,0,.2);text-align:center}h1{color:#333;font-size:24px;margin-bottom:16px}p{color:#555;font-size:16px;margin-bottom:20px}.message{font-size:16px;color:#555;margin-bottom:24px;line-height:1.5}.button{background-color:#f9c74f;color:#fff;padding:12px 25px;text-decoration:none;font-size:16px;border-radius:5px;display:inline-block;transition:background-color .3s ease}.button:hover{background-color:#e5b800}.footer{font-size:14px;color:#777;margin-top:20px}.footer a{color:#f9c74f;text-decoration:none}.footer a:hover{text-decoration:underline}</style><div class=container><h1>¡Cambio de contraseña exitoso!</h1><p>Hola {{name}},<p class=message>Tu contraseña ha sido cambiada correctamente. Si no realizaste este cambio o crees que alguien más ha accedido a tu cuenta, por favor contáctanos de inmediato.</p><a class=button href="[Enlace a Soporte]">Contactar soporte</a><div class=footer><p>Gracias por confiar en nosotros.</div></div>`;

export const EMAIL_TEMPLATES = {
  verification: TEMPLATE_EMAIL_VERIFIED,
  welcome: TEMPLATE_EMAIL_WELCOME,
  forgotPassword: TEMPLATE_EMAIL_FORGOT_PASSWORD,
  succesChangePassword: TEMPLATE_EMAIL_SUCCESS_FORGOT_PASSWORD,
};
